version: "3.3"

services:
  postgres:
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  back:
    build: ./payment_forms
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./payment_forms:/usr/src/app
    environment:
      - DEBUG=${DEBUG}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}
      - HOST=${HOST}
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_PUBLIC_API_KEY=${STRIPE_PUBLIC_API_KEY}
 

  nginx:
    build: ./nginx
    restart: always
    links:
      - back:back
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./payment_forms/static:/var/www/static
